### ISSUE TITLE
잘하고있읍니까?

### ISSUE THREAD

**Issue by hun-ca** [MINRYUL/algorithm#1]
이것도 커밋됌

**Comment by MINRYUL** [comment]
??


2021년 2월 5일 (금) 오후 8:55, Hoon <notifications@github.com>님이 작성:

**Comment by hun-ca** [comment]
커밋할거 없는날 이거쓰면 잔디밭 가능

**Comment by MINRYUL** [comment]
ㅋㅋ 너무 의미없는거 아니냐

2021년 2월 5일 (금) 오후 8:59, Hoon <notifications@github.com>님이 작성:

**Comment by MINRYUL** [comment]
fuck
